"vim
set nu
set nuw=1
set cursorline
nmap w :w<CR>
nmap q :q<CR>
"plugin
call plug#begin('~/.vim/plugged')
Plug 'Yggdroot/indentLine'
Plug 'vim-pandoc/vim-pandoc-syntax'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'neoclide/coc.nvim',{'branch':'release'}
call plug#end()
let g:airline_theme='luna'
let g:airline_powerline_fonts=1
let g:indentLine_char_list=['┆','│']
autocmd BufRead,BufNewFile * set noexpandtab
autocmd BufRead,BufNewFile *.md set filetype=markdown.pandoc
autocmd BufRead,BufNewFile * if expand('%:e')!='md'|set nowrap|endif
autocmd BufRead,BufNewFile *.json,*.md let g:indentLine_conceallevel=0
"coc.nvim
hi CocFloating ctermfg=white ctermbg=darkblue
inoremap <expr> <CR> coc#pum#visible()?coc#_select_confirm():'<CR>'
