"vim
set nu
set nuw=1
set nowrap
set cursorline
map w :w<CR>
map q :q<CR>
"plugin
call plug#begin('~/.vim/plugged')
Plug 'Yggdroot/indentLine'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'neoclide/coc.nvim',{'branch':'release'}
call plug#end()
let g:airline_theme='luna'
let g:airline_powerline_fonts=1
let g:indentLine_conceallevel=0
let g:indentLine_char_list=['┆','│']
"coc.nvim
hi CocFloating ctermfg=white ctermbg=darkblue
inoremap <expr> <CR> coc#pum#visible() ? coc#_select_confirm() : "\<CR>"
function! CheckBackspace() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~ '\s'
endfunction
inoremap <silent><expr> <TAB> coc#pum#visible() ? coc#pum#next(1): CheckBackspace() ? "\<Tab>" : coc#refresh()
inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"
